#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Feb 08 20:27:13 EST 2024
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 272b2ac6a78f4ab4a84ff7896f27834b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Lab_1_behav xil_defaultlib.Lab_1 -log elaborate.log"
xelab -wto 272b2ac6a78f4ab4a84ff7896f27834b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Lab_1_behav xil_defaultlib.Lab_1 -log elaborate.log

